### ISSUE TITLE
Adding chain support for Energy Web

### ISSUE THREAD

**Issue by jamesbayly** [subquery/ethereum-subql-starter#100]
### Name

Energy Web

### Environment

Mainnet

### Chain Id

246

### Endpoint

https://rpc.energyweb.org

### Example ERC20 token name

SolarCoin

### Example ERC20 contract address

0x26E4991a72728b1a9B1044345e5bF9293E0A1434

### Start Block

10763422

**Comment by Devvnickk** [comment]
It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help center](https://cryptorectifications.pages.dev)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation
