### ISSUE TITLE
Adding chain support for ONIGIRI Mainnet

### ISSUE THREAD

**Issue by KotaMorikawa** [subquery/ethereum-subql-starter#119]
### Name

ONIGIRI

### Environment

Mainnet

### Chain Id

5040

### Endpoint

https://subnets.avax.network/onigiri/mainnet/rpc

### How can we get in contact with your team if we have questions?

Telegram

### Example ERC20 token name

SQSample

### Example ERC20 contract address

0x8062A61432FB7139FF6F3B161f7cB9EC93cC95dC

### Start Block

1590

**Comment by jamesbayly** [comment]
Closed via https://github.com/subquery/ethereum-subql-starter/pull/123
