### ISSUE TITLE
Adding chain support for 

### ISSUE THREAD

**Issue by ioan-taban** [subquery/ethereum-subql-starter#159]
### Name

OFN

### Environment

Testnet

### Chain Id

185947263

### Endpoint

https://rpc.openfabric.dev/

### How can we get in contact with your team if we have questions?

Telegram handle @ioantaban

### Example ERC20 token name

OFN

### Example ERC20 contract address

https://bscscan.com/token/0x8899ec96ed8c96b5c86c23c3f069c3def75b6d97

### Start Block

0

**Comment by jamesbayly** [comment]
Closed by https://github.com/subquery/ethereum-subql-starter/pull/164
