### ISSUE TITLE
Adding chain support for 

### ISSUE THREAD

**Issue by oyyblin** [subquery/ethereum-subql-starter#161]
### Name

Gravity Alpha Mainnet

### Environment

Mainnet

### Chain Id

1625

### Endpoint

https://rpc.gravity.xyz

### How can we get in contact with your team if we have questions?

tg @oyyblin

### Example ERC20 token name

WETH

### Example ERC20 contract address

0xe2913E5d24E42303E7D4B2a5BF3f9D2Ccd399424

### Start Block

24

**Comment by jamesbayly** [comment]
Closed by https://github.com/subquery/ethereum-subql-starter/pull/162
