### ISSUE TITLE
Adding chain support for Citrea

### ISSUE THREAD

**Issue by muhylmz** [subquery/ethereum-subql-starter#169]
### Name

Citrea

### Environment

Testnet

### Chain Id

5115

### Endpoint

https://rpc.testnet.citrea.xyz

### How can we get in contact with your team if we have questions?

You can write me on telegram, @myilmaz3 

Also we have a dedicated group chat. 

### Example ERC20 token name

USDC

### Example ERC20 contract address

0xb669dC8cC6D044307Ba45366C0c836eC3c7e31AA

### Start Block

107453

**Comment by jamesbayly** [comment]
https://github.com/subquery/ethereum-subql-starter/commit/7bdbf7f4643c69622155dc14dbd8170f1e459e7a
